### ISSUE TITLE
Project files changes not affected into htdocs

### ISSUE THREAD

**Issue by hariprasathinvenzo** [andregugliotti/docker-nginx-php7-mysql#2]
Hi Bro,

 we followed your guide everything works fine from htdocs.

How can i make like project as local and htdocs as live please help.

ex: we modified the index.php inside the project files and made docker-compose down and up again but the changes not affected.

**Comment by hariprasathinvenzo** [comment]
And couple of things i wanted to mention
1. alpine container was exited automatically.
2. For consul there is no ports assigned

**Comment by Djuki** [comment]
@hariprasathinvenzo to avoid alpine container from exiting replace command `true` with `tail -f /dev/null`

Now the `docker-compose.yml` look like this

```
project:
  image: alpine:latest
  volumes:
    - ../htdocs:/var/www/htdocs
  command: "tail -f /dev/null"
  ```
